services:
  mysql:
    image: mysql:8.0.23
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=mangobyte
      - MYSQL_PASSWORD=mang0byte
      - MYSQL_DATABASE=accounts
    command: 
      - --sql_mode=

  account-service:
    build:
      context: ./account-service
      target: base
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysql/accounts
      - MYSQL_USER=mangobyte
      - MYSQL_PASSWORD=mang0byte
      - SHOW_SQL=false
      - DDL_AUTO=create
networks:
  default:
    name: microservice_network
