services:
  mysql:
    image: mysql:8.0.23
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=mangobyte
      - MYSQL_PASSWORD=mang0byte
      - MYSQL_DATABASE=accounts
    command: 
      - --sql_mode=

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminP@assword
      - MONGO_INITDB_DATABASE=mydatabase

  account-service:
    build:
      context: ./account-service
      target: base
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysql/accounts
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=adminP@assword
      - SHOW_SQL=false
      - DDL_AUTO=create

  message-service:
    build:
      context: ./message-service
      target: base
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017
      - MONGODB_DATABASE_NAME=chat
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=adminP@assword

networks:
  default:
    name: microservice_network
