services:
  mysql:
    extends:
      file: ./docker-compose.base.yml
      service: mysql

  account-service:
    extends:
      file: ./docker-compose.base.yml
      service: account-service
    build:
      target: test
networks:
  default:
    name: microservice_network
